trigger:
- main

variables:
  dockerRegistryServiceConnection: 'dockerRegistryConnection'
  imageRepository: 'mydockeruser/voting-app'
  containerRegistry: 'mydockeruser'
  kubernetesServiceConnection: 'kubernetesServiceConnection'
  aksClusterResourceGroup: 'aks-resource-group'
  aksClusterName: 'aks-cluster'
  azureSubscription: 'azureSubscription'  # Utilisation de la connexion azureSubscription

stages:
- stage: ProvisionInfrastructure
  jobs:
  - job: Terraform
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - script: |
        #!/bin/bash
        curl -LO https://releases.hashicorp.com/terraform/0.14.4/terraform_0.14.4_linux_amd64.zip
        unzip terraform_0.14.4_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        sudo chmod +x /usr/local/bin/terraform
        terraform -v
      displayName: 'Install Terraform'

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: './terraform'
        environmentServiceNameAzureRM: '$(azureSubscription)'  # Utilisation de azureSubscription
        commandOptions: '-auto-approve'
      displayName: 'Run Terraform to Provision AKS'

- stage: Build
  dependsOn: ProvisionInfrastructure
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        cd frontend
        npm install
        npm run build
      displayName: 'Build Frontend'

    - task: Docker@2
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(containerRegistry)/voting-app-frontend'
        command: 'buildAndPush'
        Dockerfile: '**/frontend/Dockerfile'
        tags: |
          $(Build.BuildId)
      displayName: 'Build and Push Frontend Docker Image'

    - script: |
        cd backend
        npm install
      displayName: 'Install Backend Dependencies'

    - task: Docker@2
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(containerRegistry)/voting-app-backend'
        command: 'buildAndPush'
        Dockerfile: '**/backend/Dockerfile'
        tags: |
          $(Build.BuildId)
      displayName: 'Build and Push Backend Docker Image'

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: '$(azureSubscription)'  # Utilisation de azureSubscription
              azureResourceGroup: '$(aksClusterResourceGroup)'
              kubernetesCluster: '$(aksClusterName)'
              namespace: 'default'
              command: 'apply'
              useConfigurationFile: true
              configuration: |
                helm upgrade --install frontend ./helm-charts/frontend --set image.repository=$(containerRegistry)/voting-app-frontend --set image.tag=$(Build.BuildId)
                helm upgrade --install backend ./helm-charts/backend --set image.repository=$(containerRegistry)/voting-app-backend --set image.tag=$(Build.BuildId)
            displayName: 'Deploy to AKS'
